use_frameworks!

pod 'Alamofire-SwiftyJSON', git: 'https://github.com/pietrorea/Alamofire-SwiftyJSON.git'
pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'

target 'NCMB-Facebook-use-framework_Example', :exclusive => true do
  pod 'NCMB-Facebook-use-framework', :path => '../'
end

target 'NCMB-Facebook-use-framework_Tests', :exclusive => true do
  pod 'NCMB-Facebook-use-framework', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
